title: The 2nd   <br>
IEG LivArch-Workshop  <br>
– “Sensitivities, Trauma, and Sociability” –
description: February 20th 2026, 10 am - 5 pm (CET), online only
show_downloads: true
google_analytics:
theme: jekyll-theme-tactile
remote_theme: pages-themes/tactile@v0.2.0

